### ISSUE TITLE
FLIRT scaling based on scl_slope / scl_inter

### ISSUE THREAD

**Issue by pfuchs** [o-snow/QSM_TiltCorrection#3]
Flirt applies scaling based on the header intercept and slope values, but the output nifti does not contain these anymore (i.e. slope is set to 1 and intercept to 0), resulting in erroneous scaling of the input nifti_struct if these values are not 1/0 on input.

**Comment by o-snow** [comment]
Thanks, Patrick. Where is the slope and intercept set to 1 and 0? It should not be changed from the input within our function. Are you saying that the flirt output changes the input header information from an original slope and intercept to 1 and 0?

**Comment by pfuchs** [comment]
Yes, and it scales the image according to intercept snd slope (most likely prior to interpolation, but not sure). Resulting in a scaled output of FLIRT

**Comment by o-snow** [comment]
Thanks, Patrick. I have now altered RotateNifti.m to change the header information to prevent any scaling, and then to put the header information back to what it originally was after rotation.
